export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INITIALIZE_INGREDIENTS =  "INITIALIZE_INGREDIENTS";
export const BURGER_INITIALIZE_ERROR = "BURGER_INITIALIZE_ERROR";
export const START_PURCHASE = "START_PURCHASE";
export const PURCHASE_COMPLETED = "PURCHASE_COMPLETED";
export const PURCHASE_ERROR = "PURCHASE_ERROR";
export const PURCHASE_INIT = "PURCHASE_INIT";